### ISSUE TITLE
Fails on Windows 7

### ISSUE THREAD

**Issue by ShaneCourtrille** [zewa666/generator-aurelia#1]
Fresh node/npm/jspm install.  When I tried to use it I got this:

C:\Users\scourtrille\AppData\Roaming\npm\node_modules\generator-aurelia\app\index.js:6
  var files   = this.expandFiles('*_/_', { cwd: this.sourceRoot(), dot: true }
                                                     ^
TypeError: Object [object Object] has no method 'sourceRoot'

**Comment by zewa666** [comment]
Thanks for the hint. There was a breaking change in the Yeoman API, got it fixed. Just fire the command `npm install -g generator-aurelia` again and then it should work

**Comment by ShaneCourtrille** [comment]
Thanks for the awesome response time.  Fixed.

**Comment by zewa666** [comment]
You are welcome thx again for reporting it
