### ISSUE TITLE
App doesn't work

### ISSUE THREAD

**Issue by AshleyGrant** [zewa666/generator-aurelia#12]
When I run `yo aurelia` then `gulp watch` I'm getting:

``` bash
Failed to load resource: the server responded with a status of 404 (Not Found)
2:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1444 Unhandled promise rejection Error loading "main" at http://localhost:9000/dist/main
Not Found: http://localhost:9000/dist/main
```

A user in the gitter channel mentioned this. I don't have this problem when downloading the skeleton release zip.

**Comment by zewa666** [comment]
@AshleyGrant  This error happens when you've not installed jspm@beta. Make sure to install it before launching the yeoman generator. I've just tried it again and it works properly

**Comment by AshleyGrant** [comment]
I have the beta installed. That's not the problem.

**Comment by zewa666** [comment]
hmm really not sure why, as it does nothing else then downloading the latest available tag and running npm and jspm in the background. The error besides that specifically always happened with an outdated JSPM version. Could you maybe try it again?

**Comment by andyshora** [comment]
Switching to the beta release fixed it for me. Added a [pull request](https://github.com/zewa666/generator-aurelia/pull/13) to update the docs.

**Comment by AshleyGrant** [comment]
@zewa666 and I think this was a transient issue in the Aurelia Skeleton's master branch. The generator was pulling from master instead of the latest release tag. It seems to have gone away now.

**Comment by zewa666** [comment]
Thats right, the new version only fetches the latest release tag
