### ISSUE TITLE
'yo aurelia' fails behind corporate proxy

### ISSUE THREAD

**Issue by TWry** [zewa666/generator-aurelia#17]
When I do 'yo aurelia', I'm getting an error from the corporate proxy server that says:

```
Error aurelia
Failed to get latest release info. Reason: 
[html page saying that a GET request to 
http://api.github.com:443/repos/aurelia/skeleton-navigation/tags cannot be completed]
```

When I try to submit that same request using curl, I'm getting the same error. If I use https://api.github.com:443/repos/aurelia/skeleton-navigation/tags, I'm getting a proper response.

Is there anything I can configure to make yeoman use https instead of http or is there some other workround?

**Comment by zewa666** [comment]
hmmm this is really strange since https is setup as protocoll https://github.com/zewa666/generator-aurelia/blob/master/app/index.js#L23

I'll dig it up and see what I can do. The used node module is called [Node-Github](https://github.com/mikedeboer/node-github)

EDIT:
There seems to be a proxy settings, https://github.com/mikedeboer/node-github/pull/102 can I ask you to open the globally installed generator code and try adding the proxy part. Its hard for me to test and would be best if solved under your actual circumstances. If it works we can add a flag to start it up like: `yo aurelia --proxy=...`

**Comment by TWry** [comment]
I'm not sure what I need to add in which file. Could you advise, please?

Please note that I have set the HTTP_PROXY / HTTPS_PROXY environment variables (both in uppercase and lowercase versions). What's odd is that a request to https://api.github.com:443/repos/aurelia/skeleton-navigation/tags works ok but http://api.github.com:443/repos/aurelia/skeleton-navigation/tags (note the different protocol!) will not got through using curl. 

When I look at the first code reference you provided, it seems to me that generator-aurelia is working correctly but some downstream module translates the https request to http on port 443.

**Comment by zewa666** [comment]
@TWry please try the following. Locate the globally installed generator (on windows -> `User\{YourUserName}\AppData\Roaming\npm\node_modules\generator_aurelia` and open the file `app/index.js`. In the GitHubApi config add this after the header:

`proxy: "http://YOURPROXYHERE:YOURPORT"`, so it looks like as follows:

```
var github = new GitHubApi({
      // required
      version: "3.0.0",
      debug: true,
      protocol: "https",
      host: "api.github.com",
      pathPrefix: "",
      timeout: 30000,
      headers: {
        "user-agent": "Aurelia-Github-Loader"
      },
        proxy: "YOURPROXYHERE:YOURPORT"
    });
```

please tell me if that works for you

**Comment by cmoesel** [comment]
Thanks for the tip @zewa666.  I was running into a similar issue, but my error was `Failed to get latest release info. Reason: connect ECONNREFUSED`. I tried your fix and it just changed the reason-- so now it is: `Failed to get latest release info. Reason: socket hang up`.  My corporation also does SSL certificate rewriting, so I wonder if perhaps that's the issue now?

**Comment by zewa666** [comment]
I've tested the application now behind a proxy implementation as well and got the same error with `socket hang up` ... so far I have no idea how to fix that

**Comment by igitur** [comment]
I get the same behind my corporate proxy. Here is a screenshot of a Wireshark trace that captures the error.

![image](https://cloud.githubusercontent.com/assets/145854/10799687/c0709b68-7db6-11e5-8dc1-839181c18fb0.png)

**Comment by er1x** [comment]
I think it's a problem with node-github package. I was able to fix the error patching it with [this PR](https://github.com/mikedeboer/node-github/pull/282/commits).

**Comment by zewa666** [comment]
@cmoesel and @igitur, can you guys give the fix mentioned by @er1x a try and see whether that works for you?

**Comment by igitur** [comment]
@er1x 's fix works for me.

**Comment by zewa666** [comment]
if now @cmoesel can confirm as well I'll gladly point to the mentioned PR instead of the original source until this one gets merged.

**Comment by cmoesel** [comment]
I'll try to find some time to give it a shot today.  Will let you know...

**Comment by cmoesel** [comment]
I had to apply both fixes mentioned here:
1. @zewa666's fix to add the proxy to generator-aurelia/app/index.js
2. @er1's fix to use the node-github PR

The first fix took care of my  `ECONNREFUSED` problem.  The second took care of my `socket hang up` problem.  Thanks for the fixes!

**Comment by zewa666** [comment]
@cmoesel, @igitur I've released a new version of the generator, so please update it and try it out. The new syntax would be:

```
yo aurelia --proxy=http://your.proxy:YOURPORT
```

**Comment by igitur** [comment]
Works for me, even if I do just `yo aurelia`. But maybe it's because I've set my npm proxy recently. Can't remember whether I did that before or after I started experiencing this issue.

**Comment by TWry** [comment]
Working ok here as well. No --proxy necessary if it is set in the environment. Thanks!

**Comment by cmoesel** [comment]
Looks good to me.  Note that I _did_ have to use the `--proxy=http://your.proxy:YOURPORT` flag for it to work.  Otherwise I got the `ECONNREFUSED` error.  With the _proxy_ flag, it works wonderfully.  Thanks!

**Comment by zewa666** [comment]
@igitur, @TWry and @cmoesel thank you guys for the responses and tests :+1: 

as soon as the PR gets merged I'll switch the npm repo again
