### ISSUE TITLE
Generator does not use jspm GitHub credentials

### ISSUE THREAD

**Issue by mewejo** [zewa666/generator-aurelia#18]
No where in the app/index.js file is there a line to authenticate with GitHub.

Pulled my hair out for a while and then hacked my local file and hard coded my credentials in after the github instance was created.

Am I missing something?

``` javascript
github.authenticate(
{
    type: "basic",
    username: 'mewejo',
    password: 'xxxxxxxx'
});
```

**Comment by mewejo** [comment]
I was being hit with the rate limit error FYI.

**Comment by zewa666** [comment]
ohoo ... didn't think about that. 
We could create a setup routine, called e.g. via `yo aurelia --github` and then be asked for the necessary information and store them for the next use.

what do you think about that? any other ideas?

**Comment by andyshora** [comment]
It told me my rate limit was exceeded on the first attempt at `yo aurelia`

**Comment by scrapcupcake** [comment]
Getting bitten by this right now; generator will just fail for me for the next forty minutes or so until the rate limit is up, yay. Wish I'd known before I ran the generator the first time; if you don't have jspm creds already set up, you _will_ run into the rate limit running this command; then, after setting up jspm correctly, whatever the generator is doing with the github api prior to jspm will fail and you'll just get locked out of developing; horrible first time experience, if this is meant to be the face of the project, which the docs sure make it seem like they are.

Probably worth calling out a bit stronger in the docs; not a sidenote, but a full punchout block describing that setting up jspm credentials properly is essentially _required_ to not be locked out of the experience.

**Comment by boedy** [comment]
@scrapcupcake +1

I Tried using username & password. This didn't remove the error for me. Using a token however solved it.

**Comment by zewa666** [comment]
@scrapcupcake thanks for the info you're right that makes more sense now. I simply forgot to draw more attention on that one since jspm support came after few iterations. Good point and its already updated :+1:
