### ISSUE TITLE
yo aurelia gives "Error: spawn ENOENT"

### ISSUE THREAD

**Issue by maskmaster** [zewa666/generator-aurelia#2]
Tested with
generator-aurelia v. 0.3.1
nodejs v. 0.10.33 and 0.11.14
yeoman v. 1.3.3

Error: spawn git ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1038:32)

The error message applies to nodejs v. 0.11.14

**Comment by zewa666** [comment]
Do you have git installed? Which OS are you using? Please try to run the command either as sudo or in Win by opening the CMD Line as Administrator.

**Comment by maskmaster** [comment]
Spot on! It was git that was missing. Git apparently wasn't kept when I upgraded Ubuntu. Thank you for the quick response. Sorry for the trouble.

**Comment by zewa666** [comment]
No trouble at all, good hint actually will update the readme
