### ISSUE TITLE
Not showing menus and first page

### ISSUE THREAD

**Issue by rof20004** [zewa666/generator-aurelia#24]
After yo aurelia, npm install and jspm install, i did gulp watch but onlye show the page with "AURELIA NAVIGATION SKELETON" and the spinner/loader, not show menus. I tried to enter in welcome page but not working, the error shows in my console:

TypeError: object is not a function {stack: (...), message: "object is not a function"} - shim.min.js:1773

I go to line, and this is the line:

g ? (f || (b.h = !0), c = g === !0 ? e : g(e), c === a.promise ? d(TypeError("Promise-chain cycle"))

I do not know why.

**Comment by zewa666** [comment]
the generator was still running on the old version which did jspm/npm installs in the bad location. I've updated the generator to ask you now which skeleton version you'd like to work with. So please try it out with the new version by updating the generator

**Comment by rof20004** [comment]
Thanks, I will try tonigth.

**Comment by rof20004** [comment]
Sorry, I tried and the error persist.

TypeError: object is not a function :9000/jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1773 

I check the code:

d(TypeError("Promise-chain cycle"))

I did not changed yet, but first i need to know with someone else get this error.

**Comment by rof20004** [comment]
I check and url.

http://localhost:9000/users

shows this message: Cannot GET /users

Only first screen shows, the others(welcome, users and child-router) not.

**Comment by zewa666** [comment]
do you experience the same issue when installing the skeleton manually?

**Comment by rof20004** [comment]
I did not tried manually, i will try now, can you provide me a tutorial for this ? steps to do it ?

Thanks.

**Comment by zewa666** [comment]
sure, essentially you just clone `https://github.com/aurelia/skeleton-navigation`, go to the folder of the version you'd like (e.g EcmaScript 2016 -> skeleton-es2016) and read the according README file for further instructions.

If you experience any troubles please join our gitter channel where currently 2,5k ++ users can help you out.

https://gitter.im/Aurelia/Discuss

Thanks for your help

**Comment by rof20004** [comment]
I tried manually too, but the same error, I logged in discuss, feel free to close this issue if you want.

**Comment by rof20004** [comment]
After use yo aurelia, to correct this issue:

Inside the project that you have choosen:

**Comment by rof20004** [comment]
jspm install aurelia-framework aurelia-bootstrapper aurelia-loader-default aurelia-templating-resources aurelia-event-aggregator aurelia-templating-router aurelia-history-browser aurelia-logging-console aurelia-templating-binding core-js text

**Comment by rof20004** [comment]
after

**Comment by rof20004** [comment]
jspm dl-loader --latest

**Comment by rof20004** [comment]
Now it worked for me.

Ecmas2016
