### ISSUE TITLE
Installs every NPM module

### ISSUE THREAD

**Issue by bbrewder** [zewa666/generator-aurelia#27]
I've tried running "yo aurelia" a couple times now, and each time it installed what seems like every NPM module. It took a few hours, was nearly 4 gigs, and over 700 directories under node_modules. If it matters, I picked the "EcmaScript 2016" template. 

I am following the PluralSight course "Aurelia Fundamentals" and so I believe I have all the basics installed correctly (npm, jspm, grunt, yoeman). Everything was installed tonight (I'm new to these tools), and I did make sure I updated to the latest version of npm (apparently the version that can be installed from their site is out of date).

**Comment by bbrewder** [comment]
I updated Yoeman today and tried again. Now it is "only" 250 MB of files.

**Comment by zewa666** [comment]
Yeah I remember having that once with old version of both yeoman and npm. I'm not sure there is anything I can do here about that, sadly its more an issue with the used tools, so I'm going to close this. We can although open it if you see any concrete things we can tackle
