### ISSUE TITLE
Generator not working

### ISSUE THREAD

**Issue by smahi** [zewa666/generator-aurelia#28]
The generator is not working properly on my dev box it shows the following err

? Which Aurelia preset would you like to install? EcmaScript 2016
/Users/smahi/Sites/Aurelia-Projects/demo-gulp
     info Downloading latest available release: 1.0.0-beta.1.3.1
✔ Download complete
     info Running non-windows platform (darwin)
Error aurelia 

Command failed: /bin/sh -c mv -v "/Users/smahi/Sites/Aurelia-Projects/demo-gulp/github_tmp/skeleton-es2016/"\* "/Users/smahi/Sites/Aurelia-Projects/demo-gulp/"
mv: rename /Users/smahi/Sites/Aurelia-Projects/demo-gulp/github_tmp/skeleton-es2016/\* to /Users/smahi/Sites/Aurelia-Projects/demo-gulp/*: No such file or directory

It seems that  the ES6 skeleton folder has been renamed from **_skeleton-es2016_** to **_skeleton-esnext_**

**Comment by atsu85** [comment]
I guess this project is deprecated in favour aurelia-cli that was announced yesterday

**Comment by smahi** [comment]
Thank you very much
