### ISSUE TITLE
6to5 name change to babel

### ISSUE THREAD

**Issue by maskmaster** [zewa666/generator-aurelia#3]
6to5 recently changed name to babel, you get a deprecation warning when doing fresh 'npm install' in a skeleton app.

**Comment by zewa666** [comment]
Hi there,

this is actually something that needs to be fixed in Aurelia's skeleton directly, since it's no direct requirement of the generator. Could you maybe post an issue in the aurelia repo?

**Comment by zewa666** [comment]
This should be fixed by now as the Skeleton Navigation App got updated.
