### ISSUE TITLE
Adding a page in a sub folder to make the structure highly maintainable

### ISSUE THREAD

**Issue by manumqln** [zewa666/generator-aurelia#30]
How to add a page in a sub folder to make the structure highly maintainable? For example, I need to create an about component inside a sub folder 'about' using the page creation command. How can I do that?

**Comment by zewa666** [comment]
just name it `about/about`

`yo aurelia:page about/about`

**Comment by manumqln** [comment]
I tried it but this causes an error in the component JS file due to an extra slash.

**Comment by zewa666** [comment]
my bad, yeah just seen it after looking at it :)

I've pushed a new version, you should update your yo aurelia generator and than it should work

**Comment by manumqln** [comment]
Yep, no worries. I will check it. Thanks for the swift action.
