### ISSUE TITLE
npm install before you can gulp watch?

### ISSUE THREAD

**Issue by dtanner** [zewa666/generator-aurelia#4]
Hi,

I'm still pretty new with node, so not sure if this was a problem that only I had, or if this step is missing from the Running The App tutorial...I needed to do an `npm install` in the directory to install the app dependencies before I could run with gulp watch.

**Comment by zewa666** [comment]
You mean like step 5 or something different?

**Comment by dtanner** [comment]
ha!  yeah, like that step :-)   I missed it - thanks for the clarification.
