### ISSUE TITLE
Add option to automatically run npm install and jspm install

### ISSUE THREAD

**Issue by delebash** [zewa666/generator-aurelia#5]
Nice feature would be to automatically run npm and jspm install

Thanks,
Dan

**Comment by zewa666** [comment]
Like do that after it downloaded and scaffolded the app? Not sure whether this involves additional permissions (e.g. sudo on Mac or Admin Mode on Windows) in which case it could become less usable. I'll take a look, let's see what we can do :)

**Comment by delebash** [comment]
Yes after it downloads the app.  I have seen other generator do this same thing, I think the polymer generator does this, after it downloads it runs npm install and bower install automatically, so maybe look and see how they are doing it. 

Thanks.

**Comment by zewa666** [comment]
I've updated the generator to do an automatic `npm install`. As for jspm I'm not really sure what to do. The JSPM API seems to have a problem regarding the proper executionLocation so I'll need to check that in detail when back home on my proper PC :)

Nevertheless I'd kindly ask you to try out the new generator and see if the npm install happens automatically.

Thanks in advance

**Comment by delebash** [comment]
Just tested your update
npm automatic install works great, thanks for the quick enhancement!

Let me know when you get jspm install working and I will be glad to test that as well

**Comment by zewa666** [comment]
ok think I got that setup. Thanks for testing the npm stuff now if I could ask you to do it one more time that'd be awesome :) This time npm + jspm should run automatically

**Comment by delebash** [comment]
Works great, both npm and jspm install run automatically 
Thank you very much for making this generator!!

**Comment by zewa666** [comment]
You're welcome. THX for the request this really improves the UX of the generator.
