### ISSUE TITLE
Generator not getting latest skeleton

### ISSUE THREAD

**Issue by delebash** [zewa666/generator-aurelia#7]
Generator version is the latest 3.3

There has been a new release of Aurelia and the skeleton-app but the generator still seems to be pulling the previous version.  I don't see anything in the generator code that specifies a version, but I am not very familiar with creating a generator although it looks fairly straight forward.

I thought maybe I was pulling it from a cached version but I don't see how?

Thanks,
Dan

**Comment by zewa666** [comment]
Hmm maybe it was an issue with regards to timing :)

I've tried it just now and got the latest release installed. Could you please try once more and see if that still happens?

Btw. thank you for your help and testing out stuff :+1:

**Comment by delebash** [comment]
I just ran it and it is still pulling the old src.  This is from folder src/app.js in skeleton-nav
export class App {
  static inject() { return [Router]; }

It should have the new Decorator style for inject, if I just manually download the git repo for the skeleton-nav it has the updated source code "@inject(Router) export class App {"

Glad I can help, and thank you guys for Aurelia really like working with it.

**Comment by delebash** [comment]
If you look in npm\node_modules\generator-aurelia\app\templates there is a cache of the skeleton-nav, it is the old version, I tried clearing npm cache and uninstalling and reinstalling the generator but it still creates the old version when you install the generator

**Comment by zewa666** [comment]
that mentioned cache is actually a git sub-repository. If you look here https://github.com/zewa666/generator-aurelia/blob/master/app/index.js#L11 you'll see that on scaffolding the generator updates all of those. So what could be a problem maybe is that it silently fails because of some access restrictions.

What OS are you running? If Linux/Mac could you try using sudo, on Windows start the cmd as Administrator.

EDIT:
Also please make sure that git is available and accessible from the cmd/terminal/whatever

**Comment by delebash** [comment]
Windows 7 x64
npm version 2.7.4
iojs/node version 1.6.3 

Running cmd as administrator
Steps to reporduce

1) ran npm -g uninstall generator-aurelia
2) ran npm cache clear
3) ran npm -g install generator-aurelia
git runs fine from cmd line 

After the initial install of generator-aurelia , before even running yo aurelia, the generator connects to github and downloads the scaffold.  I can check the directory after the initial install and verify it has already downloaded the old code, again this is even before running yo aurelia, it downloads old code on the initial install.  It can't be pulling old code from cache because I cleared it already and verified there is nothing in npm_cache

Verified that E:\Program Files\iojs\global_npm\npm\node_modules\generator-aurelia\app\templates\src\app.js does not have the Decorator syntax

Very strange problem....

I can work around it by just updating the template directory manually with the latest code from github, but then it is not automatically kept up to date as new skeleton-nav releases are available.

I will keep, looking but right now I don't have any idea as to what the problem is or where else to check, let me know if you have any ideas on where to look for the problem or what you would like me to try.

Thanks for your help

**Comment by zewa666** [comment]
Can anyone else reproduce the same issue? I've tried it now on three different stations and not able to do so. An alternative would be to switch away from sub-repositories but I'd like to keep that as a last option

**Comment by joshrivers** [comment]
I just re-installed the generator and ran it, and I'm getting the outdated template as well, on MacOS.

**Comment by zewa666** [comment]
ok thanks for the hints now I've been able to reproduce the bug as well. Typically I worked by linking the local repo to global install, so it seems like the git updater doesn't work as expected. Now at least I can test it properly.

**Comment by zewa666** [comment]
Ok @joshrivers and @delebash there is a new update which hopefully should fix the issue. May I ask you both to check it out and see whether this one works properly?

**Comment by delebash** [comment]
uninstalled and reinstalled generator, ran yo aurelia error
 yo aurelia
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: Cannot find module 'download-github-repo'
    at Function.Module._resolveFilename (module.js:316:15)
    at Function.Module._load (module.js:258:25)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at module.exports.generators.Base.extend.init (E:\Program Files\iojs\global_npm\npm\node_modules\generator-
aurelia\app\index.js:9:22)
    at E:\Program Files\iojs\global_npm\npm\node_modules\generator-aurelia\node_modules\yeoman-generator\lib\ba
se.js:409:16
    at processImmediate [as _immediateCallback](timers.js:361:17)

**Comment by zewa666** [comment]
Ahh crap didnt check in properly. Im out of home now will get it fixed
tomorrow.
Am 17.04.2015 19:49 schrieb "dan" notifications@github.com:

**Comment by zewa666** [comment]
@delebash, @joshrivers sry guys I missed checking in the dependency into the package.json file. There is a new release which should fix that.

**Comment by delebash** [comment]
Just tested and it is working fine, thanks for the fix!

**Comment by joshrivers** [comment]
Confirmed that it's running correctly for me as well. Thanks!
