### ISSUE TITLE
Fresh install gives 404 for system.js

### ISSUE THREAD

**Issue by pixels4nickels** [zewa666/generator-aurelia#8]
After following instructions for this seed I am getting 404
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9000/jspm_packages/system.js Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by zewa666** [comment]
Thanks for the information ... seems to be a general issue with the new release on the skeleton itself.

**Comment by zewa666** [comment]
@pixels4nickels after some testing it seems that something changed in jspm itself, necessary for the latest release. Please try to `npm update -g jspm` and retry the generator afterwards. That should hopefully fix it. If it still doesn't work, please try deleting the folder `jspm_packages` and running `jspm install` from the projects root afterwards.

**Comment by pixels4nickels** [comment]
I fixed it using this thread(your response works well too). Thanks so much for the quick reply!
https://github.com/aurelia/skeleton-navigation/issues/39

**Comment by zewa666** [comment]
Glad it got solved
