### ISSUE TITLE
404 errors following a fresh install

### ISSUE THREAD

**Issue by mgcrea** [zewa666/generator-aurelia#9]
Following a fresh `yo aurelia`, I end up with a broken app with 404s regarding `aurelia/templating-resources@0.13.0.js`. `jspm i github:aurelia/templating-resources` did not solve the issue. Any ideas?

**Comment by zewa666** [comment]
I've just tried it again and couldn't find any issues. Could you try to run `jspm install` again. Perhaps it also helps to delete the complete `jspm_packages` folder before doing so. Alternatively please try to run `yo aurelia` again, maybe it was just some timeout issue

**Comment by zewa666** [comment]
I'm closing this since there is no reply. If the issue exist, please reopen or recreate a new issue.
